global:
  scrape_internal: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metric_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'
          
