global:
  scrape_internal: 30s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metric_path: /metrics
    static_configs:
      - targets:
          - 'prometheus:9090'

  - job_name: node_exporter
    static_configs:
      - targets: ['localhost:9100']

  - job_name: ovs_exporter
    static_configs:
      - targets: ['localhost:9475']
